
export const SAVE_GAME_SETTINGS = 'SAVE_GAME_SETTINGS';
export const SAVE_ANSWER_INFO = 'SAVE_ANSWER_INFO';
export const END_GAME = 'END_GAME';
export const START_GAME = 'START_GAME';
export const CLEAR_GAME = 'CLEAR_GAME';
export const UPDATE_CURRENT_ANSWER = 'UPDATE_CURRENT_ANSWER';
export const SAVE_GAME_SCORE = 'SAVE_GAME_SCORE';
